# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
    # Declare a dependency on the welcome-orb
    welcome: circleci/welcome-orb@0.4.1
    node: circleci/node@2.0.2
defaults: &defaults
    working_directory: ~/repo/frontend
    docker:
        - image: circleci/node:10.14.2

jobs:
    core:
        <<: *defaults
        steps:
            - checkout

            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      - v1-dependencies-

            - run: npm install

            - run: npm ci

            - run: npm run build

            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}

            - persist_to_workspace:
                  root: ~/repo/frontend
                  paths: .
# Orchestrate  or schedule a set of jobs
workflows:
    core:
        jobs:
            - core
